// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("Shared.Models.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "12be2ff1-dd78-4030-8aad-e831ded3da39",
                            Description = "Product 1 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/1/500",
                            Price = 1000L,
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = "be910f2c-2d9d-4daf-8ee1-b0d4fb842f69",
                            Description = "Product 2 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/2/500",
                            Price = 2000L,
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = "ca443fd2-28f7-4be7-a186-bef9d7e4de67",
                            Description = "Product 3 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/3/500",
                            Price = 3000L,
                            Title = "Product 3"
                        },
                        new
                        {
                            Id = "074f2510-0c62-4038-a046-97eae672076b",
                            Description = "Product 4 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/4/500",
                            Price = 4000L,
                            Title = "Product 4"
                        },
                        new
                        {
                            Id = "f1a7a272-e2ea-4af8-85e0-434c1bd89241",
                            Description = "Product 5 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/5/500",
                            Price = 5000L,
                            Title = "Product 5"
                        },
                        new
                        {
                            Id = "a3888af5-4eec-4048-bb4d-ff05cdd88c4d",
                            Description = "Product 6 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/6/500",
                            Price = 6000L,
                            Title = "Product 6"
                        },
                        new
                        {
                            Id = "52c7466a-5f6f-4cd3-917a-7e28612f8d43",
                            Description = "Product 7 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/7/500",
                            Price = 7000L,
                            Title = "Product 7"
                        },
                        new
                        {
                            Id = "23aef7a4-f9c7-4fbf-89b0-48b9c35cc132",
                            Description = "Product 8 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/8/500",
                            Price = 8000L,
                            Title = "Product 8"
                        },
                        new
                        {
                            Id = "a7377a9f-3b3e-435d-81b3-5a6af99c0b96",
                            Description = "Product 9 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/9/500",
                            Price = 9000L,
                            Title = "Product 9"
                        },
                        new
                        {
                            Id = "5de30e2c-ba7a-4beb-9594-cad71f4a1e05",
                            Description = "Product 10 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/10/500",
                            Price = 10000L,
                            Title = "Product 10"
                        },
                        new
                        {
                            Id = "4993d38a-0e45-4668-a5ba-d68030a9de09",
                            Description = "Product 11 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/11/500",
                            Price = 11000L,
                            Title = "Product 11"
                        },
                        new
                        {
                            Id = "74f874e1-54ce-456a-8d64-1e70a00c5d92",
                            Description = "Product 12 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/12/500",
                            Price = 12000L,
                            Title = "Product 12"
                        },
                        new
                        {
                            Id = "05df5a3a-9aff-4333-ab0c-3e94eb64962d",
                            Description = "Product 13 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/13/500",
                            Price = 13000L,
                            Title = "Product 13"
                        },
                        new
                        {
                            Id = "5fd19172-99c5-49de-8f78-1e8499860e75",
                            Description = "Product 14 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/14/500",
                            Price = 14000L,
                            Title = "Product 14"
                        },
                        new
                        {
                            Id = "494ab482-6e83-421e-95af-803c46e63421",
                            Description = "Product 15 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/15/500",
                            Price = 15000L,
                            Title = "Product 15"
                        },
                        new
                        {
                            Id = "eb850dd5-d1b8-4e62-9ff9-aad719473f01",
                            Description = "Product 16 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/16/500",
                            Price = 16000L,
                            Title = "Product 16"
                        },
                        new
                        {
                            Id = "8b2b5709-e2ad-4b10-800a-ce07033e8e62",
                            Description = "Product 17 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/17/500",
                            Price = 17000L,
                            Title = "Product 17"
                        },
                        new
                        {
                            Id = "1e828d8e-ebcd-4733-80b4-fa317e2b6af2",
                            Description = "Product 18 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/18/500",
                            Price = 18000L,
                            Title = "Product 18"
                        },
                        new
                        {
                            Id = "31814aad-516e-4be5-9099-fb4cf324ab28",
                            Description = "Product 19 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/19/500",
                            Price = 19000L,
                            Title = "Product 19"
                        },
                        new
                        {
                            Id = "25c7a351-b5b8-4e70-b853-d3c2cbe1ddeb",
                            Description = "Product 20 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/20/500",
                            Price = 20000L,
                            Title = "Product 20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
